[project]
name = "ptimer"
requires-python = ">= 3.10"
readme = "README.md"
description = "Simple pomodoro timer"
license = {file = "LICENSE.txt"}

[project.optional-dependencies]
dev = [
    "flake8 ~=6.1.0"
    "black ~=23.7.0"
    "mypy ~= 1.5.1"
]

[tool.black]
line-length = 120
