[project]
name = "pom"
requires-python = ">= 3.10"
readme = "README.md"
description = "Simple pomodoro timer: pom"
license = {file = "LICENSE.txt"}

[project.optional-dependencies]
dev = [
    "flake8"
    "black"
    "mypy"
]

[tool.black]
line-length = 120
